import { GridMetaDataType } from "@acuteinfo/common-base";
export const gridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "IFSC_CODE",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowFilter: false,
    allowColumnHiding: true,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      isAutoSequence: true,
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "IFSC_CODE",
      columnName: "IFSCCode",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "BANK_NM",
      columnName: "BankName",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "DDW_DISPLAY_VALUE",
      columnName: "Facility",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      accessor: "MICR_CODE",
      columnName: "MICRCode",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "BRANCH_NM",
      columnName: "BranchName",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "ADD1",
      columnName: "Add1",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "CONTACT_DTL",
      columnName: "ContactDetail",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "CENTRE_NM",
      columnName: "CentreName",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "DISTRICT_NM",
      columnName: "DistrictName",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "STATE_NM",
      columnName: "StateName",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 300,
    },
  ],
};

export const serverGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "IFSC_CODE",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [30, 40, 50],
    defaultPageSize: 30,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "IFSC_CODE",
      columnName: "IFSCCode",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "BANK_NM",
      columnName: "BankName",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "DDW_DISPLAY_VALUE",
      columnName: "Facility",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "MICR_CODE",
      columnName: "MICRCode",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "BRANCH_NM",
      columnName: "BranchName",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "CONTACT_DTL",
      columnName: "ContactDetail",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "CENTRE_NM",
      columnName: "CentreName",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "DISTRICT_NM",
      columnName: "DistrictName",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "STATE_NM",
      columnName: "StateName",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      isAutoSequence: true,
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      accessor: "IFSC_CODE",
      columnName: "IFSCCode",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "BANK_NM",
      columnName: "BankName",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "DDW_DISPLAY_VALUE",
      columnName: "Facility",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      accessor: "MICR_CODE",
      columnName: "MICRCode",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "BRANCH_NM",
      columnName: "BranchName",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "ADD1",
      columnName: "Add1",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "CONTACT_DTL",
      columnName: "ContactDetail",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "CENTRE_NM",
      columnName: "CentreName",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "DISTRICT_NM",
      columnName: "DistrictName",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "STATE_NM",
      columnName: "StateName",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 300,
    },
  ],
};
