import { GridMetaDataType } from "@acuteinfo/common-base";

export const disburseEntryConfirmGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "UNIQUE_NO",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "calc(100vh - 219px)",
      max: "calc(100vh - 219px)",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    hiddenFlag: "_hidden",
    searchPlaceholder: "",
    footerNote: "FooterNoteMsgCfmRej",
  },
  filters: [],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 75,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "AC_NO",
      columnName: "AccountNum",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 190,
    },
    {
      accessor: "ACCT_NM",
      columnName: "AccountHolder",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 190,
      maxWidth: 290,
    },
    {
      accessor: "SANCTIONED_AMT",
      columnName: "sanctionAmount",
      sequence: 4,
      alignment: "right",
      componentType: "currency",
      width: 140,
      minWidth: 70,
      maxWidth: 160,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "EnteredBy",
      sequence: 5,
      alignment: "center",
      componentType: "default",
      width: 107,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "LIMIT_AMOUNT",
      columnName: "TotalDisburseAmount",
      sequence: 6,
      alignment: "right",
      componentType: "currency",
      width: 140,
      minWidth: 70,
      maxWidth: 160,
    },
    {
      accessor: "CONFIRMED",
      columnName: "Confirmed",
      sequence: 7,
      alignment: "center",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
