import { GridMetaDataType } from "@acuteinfo/common-base";

export const photoSignatureConfGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "CUSTOMER_ID",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [20, 30, 50],
    defaultPageSize: 14,
    containerHeight: {
      min: "calc(100vh - 219px)",
      max: "calc(100vh - 219px)",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    hiddenFlag: "_hidden",
    footerNote: "FooterNoteMsgCfmRej",
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "SrNo",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 75,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "CUSTOMER_ID",
      columnName: "CustomerId",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 190,
    },
    {
      accessor: "CUST_NM",
      columnName: "CustomerName",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 250,
      maxWidth: 350,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Maker",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 174,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "LastModifiedDate",
      sequence: 6,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 163,
      minWidth: 120,
      maxWidth: 180,
    },

    {
      accessor: "MACHINE_NM",
      columnName: "MachineName",
      sequence: 7,
      alignment: "center",
      componentType: "default",
      width: 150,
      minWidth: 150,
      maxWidth: 250,
    },
  ],
};
