import { GridMetaDataType } from "@acuteinfo/common-base";

export const ShareAppConfirmGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [20, 30, 50],
    defaultPageSize: 14,
    containerHeight: {
      min: "calc(100vh - 219px)",
      max: "calc(100vh - 219px)",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    hiddenFlag: "_hidden",
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "SrNo",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 75,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "APP_TYPE_DISP",
      columnName: "ApplicationType",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 190,
    },
    {
      accessor: "APP_NO",
      columnName: "ApplicationNo",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 350,
    },
    {
      accessor: "APP_DATE",
      columnName: "ApplicationDate",
      sequence: 5,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "APP_QUANTITY",
      columnName: "ApplicationQTY",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 180,
    },

    {
      accessor: "APP_AMT",
      columnName: "ApplicationAmt",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 120,
      minWidth: 120,
      maxWidth: 250,
    },
    {
      accessor: "ACCT_NM",
      columnName: "AccountName",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 250,
      maxWidth: 350,
    },
    {
      accessor: "ISSUE_BR",
      columnName: "IssueBranch",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 200,
      maxWidth: 250,
    },
    {
      accessor: "MODE_PAYMENT_DISP",
      columnName: "ModeOfPayment",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 250,
    },
    {
      accessor: "CONF_DISP",
      columnName: "Confirmed",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 200,
      maxWidth: 250,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "EnteredBy",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 200,
      maxWidth: 250,
    },
  ],
};
