import { GridMetaDataType } from "@acuteinfo/common-base";

export const unclaimedConfirmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "calc(100vh - 219px)",
      max: "calc(100vh - 219px)",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    hiddenFlag: "_hidden",
    searchPlaceholder: "",
    footerNote: "FooterNoteMsgCfmRej",
  },
  filters: [],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 75,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "FROM_ACCT_NO",
      columnName: "FromAccountNumber",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 190,
    },
    {
      accessor: "FROM_ACCT_NM",
      columnName: "FromAccountHolderName",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 300,
      maxWidth: 350,
    },
    {
      accessor: "TO_ACCT_NO",
      columnName: "ToAccountNumber",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 190,
    },
    {
      accessor: "TO_ACCT_NM",
      columnName: "ToAccountHolderName",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 300,
      maxWidth: 350,
    },
    {
      accessor: "PAYMENT_BY",
      columnName: "PaymentBy",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 107,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "TRF_AMT",
      columnName: "TransferAmount",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 140,
      minWidth: 70,
      maxWidth: 160,
    },
    {
      accessor: "CONFIRMED",
      columnName: "Confirmed",
      sequence: 8,
      alignment: "center",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
