import { GridMetaDataType } from "@acuteinfo/common-base";

export const gridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 50,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_CD",
      columnName: "TranCD",
      sequence: 2,
      alignment: "right",
      componentType: "default",
      width: 90,
      minWidth: 90,
      maxWidth: 170,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "Branch",
      sequence: 3,
      alignment: "right",
      componentType: "default",
      width: 80,
      minWidth: 70,
      maxWidth: 170,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "AccType",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 70,
      maxWidth: 170,
    },
    {
      accessor: "ACCT_CD",
      columnName: "AccountNum",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 170,
    },
    {
      accessor: "ACCT_NM",
      columnName: "AccountName",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 150,
      maxWidth: 300,
      showTooltip: true,
    },
    // {
    //   accessor: "STATUS",
    //   columnName: "status",
    //   sequence: 2,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 150,
    //   minWidth: 100,
    //   maxWidth: 200,
    //   color: (val, data) => {
    //     let PENDING_FLAG = data?.original?.ALLOW_FORCE_EXPIRE_FLAG;
    //     return PENDING_FLAG !== "Y" ? "green" : "red";
    //   },
    // },
    {
      accessor: "ENTERED_BY",
      columnName: "Created By",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 180,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "Created Date",
      sequence: 8,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 150,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "TRAN_DT",
      columnName: "TranDate",
      sequence: 9,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 150,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "STOCK_VALUE",
      columnName: "StockValue",
      sequence: 10,
      alignment: "right",
      isTotalWithCurrency: true,
      componentType: "currency",
      width: 150,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      accessor: "DRAWING_POWER",
      columnName: "DrawingPower",
      sequence: 9,
      alignment: "right",
      componentType: "default",
      width: 150,
      minWidth: 150,
      maxWidth: 250,
    },
  ],
};
