import { GridMetaDataType } from "@acuteinfo/common-base";
export const UserSecurity: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "AD_BILL_NO",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "50vh",
      max: "65vh",
    },
    allowFilter: false,
    allowColumnHiding: true,
    isCusrsorFocused: true,
    allowRowSelection: false,
    footerNote: "DoubleClickForEditDetail",
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Entry Date",
      sequence: 2,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "AD_BILL_NO",
      columnName: "AD Bill No.",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 100,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "CUSTOMER_ID",
      columnName: "Customer Id",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "CUST_NM",
      columnName: "Customer Name",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 400,
      minWidth: 60,
      maxWidth: 500,
    },
    {
      accessor: "REMITTANCE_CCY",
      columnName: "Currency",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 50,
      minWidth: 100,
      maxWidth: 100,
    },

    {
      accessor: "AMOUNT",
      columnName: "Amount",
      sequence: 7,
      alignment: "right",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CONF_STATUS",
      columnName: "Confirm Status",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 60,
      maxWidth: 300,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Entered by",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
