apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbs-ui-microservice-deployment
  namespace: default
  labels:
    app: cbs-ui-microservice-deployment
spec:
  selector:
    matchLabels:
      app: cbs-ui-microservice-selector
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  template:
    metadata:
      name: cbs-ui-microservice-pod
      labels:
        app: cbs-ui-microservice-selector

    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: cbs-gateway-microservice-container
          image: acuteinformatics2024/enfinitycore-dev:EnfiniteCBS_UI-25.01.00.00.270
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - touch /opt/iamnotready ; sleep 120
          # resources:
          #   limits:
          #      cpu: 1500m
          #      memory: 4Gi
          #   requests:
          #      cpu: 1000m
          #      memory: 2Gi
          # livenessProbe:
          #    httpGet:
          #       path: /actuator/health/liveness
          #       port: 9103
          #    failureThreshold: 5
          #    periodSeconds: 10
          #    timeoutSeconds: 5
          # startupProbe:
          #    httpGet:
          #       path: /actuator/health
          #       port: 9103
          #    failureThreshold: 5
          #    periodSeconds: 10
          #    initialDelaySeconds: 120
          #    timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "[ ! -f /opt/iamnotready ] || ls -ld /imready &>/dev/null"
            failureThreshold: 2
            periodSeconds: 5
            timeoutSeconds: 5
          env:
            # - name: _JAVA_OPTIONS
            #   value: >-
            #          -Djavax.net.ssl.trustStore=/opt/sslCertificate/keystore.jks
            #          -Djavax.net.ssl.trustStorePassword=citybank123
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TZ
              value: "Asia/Calcutta"
          envFrom:
            - configMapRef:
                name: cbsui-service-ip-config
        #  volumeMounts: #bind mount with host
        #  - name: ssl-config
        #    mountPath: /opt/sslCertificate
        #    readOnly: true
      #volumes:
      #- name: ssl-config
      #  configMap:
      #    name: ssl-cert-config


      imagePullSecrets:
        - name: cbs-enfinity
      terminationGracePeriodSeconds: 150

---
apiVersion: v1
kind: Service
metadata:
  name: cbs-ui-microservice-service
  namespace: default
spec:
  selector:
    app: cbs-ui-microservice-selector
  type: NodePort
  ports:
    - nodePort: 30005 ###external access port
      port: 3000 ###cluster access port
      targetPort: 3000 ###pod/container access port

