export let dateMetadataSugg = {
  disableGroupBy: "Y",
  hideFooter: false,
  hideAmountIn: true,
  retrievalType: "DATE",
  autoFetch: false,
  groupBy: [""],
  columns: [
    {
      accessor: "BRANCH_CASH_LIMIT",
      columnName: "Branch Cash Limit",
      width: 165,
      filter: "filterData",
    },
    {
      accessor: "BRANCH_CD",
      columnName: "Branch Code",
      width: 132,
      filter: "filterData",
    },
    {
      accessor: "CLOSING",
      columnName: "Closing",
      width: 100,
      filter: "filterData",
    },
    {
      accessor: "CLOSING_AMT",
      columnName: "Closing Amt.",
      width: 136,
      filter: "filterData",
    },
    {
      accessor: "CLOSING_CASH_BAL",
      columnName: "Closing Cash Bal.",
      width: 170,
      filter: "filterData",
    },
    {
      accessor: "COMP_CD",
      columnName: "Company Code",
      width: 150,
      filter: "filterData",
    },
    {
      accessor: "CURRENCY_CD",
      columnName: "Currency",
      width: 115,
      filter: "filterData",
    },
    {
      accessor: "DENO_LABLE",
      columnName: "Deno Lable",
      width: 125,
    },
    {
      accessor: "DENO_SORT",
      columnName: "Deno Sort",
      width: 125,
    },
    {
      accessor: "DENO_TYPE",
      columnName: "Deno Type",
      width: 120,
      filter: "filterData",
    },
    {
      accessor: "DENO_VAL",
      columnName: "Deno Value",
      width: 128,
      filter: "filterData",
    },
    {
      accessor: "EXCHANGE_AMT",
      columnName: "Exchange Amt.",
      width: 147,
      filter: "filterData",
    },
    {
      accessor: "OPENING",
      columnName: "Opening",
      width: 110,
      filter: "filterData",
    },
    {
      accessor: "OP_CASH_BAL",
      columnName: "Opening Cash Bal.",
      width: 170,
      filter: "filterData",
    },
    {
      accessor: "PAID_AMT",
      columnName: "Paid Amt.",
      width: 125,
      filter: "filterData",
    },
    {
      accessor: "RECEIVE_AMT",
      columnName: "Receive Amt.",
      width: 135,
      filter: "filterData",
    },
    {
      accessor: "TOT_CASH_PAY",
      columnName: "Total Cash Pay",
      width: 150,
      filter: "filterData",
    },
    {
      accessor: "TOT_CASH_REC",
      columnName: "Total Cash Rec.",
      width: 150,
      filter: "filterData",
    },
  ],
};
