import { GridMetaDataType } from "@acuteinfo/common-base";
export const SIDetailGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "StandingInstructionDetail",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    footerNote: "SITabFooterNote",
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "21.4vh",
      max: "21.4vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      alignment: "right",
      width: 50,
      maxWidth: 110,
      minWidth: 50,
    },
    {
      columnName: "StartDate",
      accessor: "START_DT",
      sequence: 2,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 110,
      maxWidth: 150,
      minWidth: 70,
    },
    {
      columnName: "Status",
      accessor: "DOC_STATUS",
      sequence: 3,
      alignment: "center",
      componentType: "editableCheckbox",
      isReadOnly: true,
      width: 80,
      maxWidth: 110,
      minWidth: 50,
    },
    {
      columnName: "DebitfromAC",
      accessor: "DR_ACCT_NO",
      sequence: 4,
      componentType: "default",
      alignment: "left",
      width: 130,
      maxWidth: 160,
      minWidth: 100,
    },
    {
      accessor: "DR_ACCT_NM",
      columnName: "DebitAcctName",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      showTooltip: true,
      width: 300,
      minWidth: 50,
      maxWidth: 350,
    },
    {
      columnName: "CreditToAccount",
      accessor: "CR_ACCT_NO",
      sequence: 6,
      componentType: "default",
      alignment: "left",
      width: 140,
      maxWidth: 160,
      minWidth: 100,
    },
    {
      accessor: "CR_ACCT_NM",
      columnName: "CreditAcctName",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      showTooltip: true,
      width: 300,
      minWidth: 50,
      maxWidth: 350,
    },
    {
      columnName: "SIAmount",
      accessor: "SI_AMOUNT",
      sequence: 8,
      componentType: "currency",
      currencyRefColumn: "CURRENCY_CD",
      alignment: "right",
      isTotalWithCurrency: true,
      totalDecimalCount: 2,
      width: 130,
      maxWidth: 160,
      minWidth: 100,
    },
    {
      columnName: "SICharge",
      accessor: "SI_CHARGE",
      sequence: 9,
      componentType: "currency",
      currencyRefColumn: "CURRENCY_CD",
      alignment: "right",
      isTotalWithCurrency: true,
      totalDecimalCount: 2,
      width: 130,
      maxWidth: 160,
      minWidth: 100,
    },
    {
      columnName: "Remarks",
      accessor: "REMARKS",
      sequence: 10,
      componentType: "default",
      showTooltip: true,
      width: 150,
      maxWidth: 180,
      minWidth: 100,
    },
    {
      columnName: "ValidUpto",
      accessor: "VALID_UPTO",
      sequence: 11,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      maxWidth: 130,
      minWidth: 70,
    },
    {
      columnName: "ExecuteOnDay",
      accessor: "EXECUTE_DAY",
      sequence: 12,
      componentType: "default",
      alignment: "right",
      width: 120,
      maxWidth: 150,
      minWidth: 90,
    },
    {
      columnName: "EnteredBy",
      accessor: "ENTERED_BY",
      sequence: 13,
      componentType: "default",
      width: 100,
      maxWidth: 130,
      minWidth: 70,
    },
    {
      columnName: "EnteredBranch",
      accessor: "ENT_BRANCH_CD",
      sequence: 14,
      componentType: "default",
      alignment: "right",
      width: 130,
      maxWidth: 160,
      minWidth: 100,
    },
    {
      columnName: "FrequncyType",
      accessor: "FEQ_TYPE_DISP",
      sequence: 15,
      componentType: "default",
      width: 130,
      maxWidth: 160,
      minWidth: 100,
    },
    {
      columnName: "DeactivedBy",
      accessor: "DEACTIVE_BY",
      sequence: 16,
      componentType: "default",
      width: 110,
      maxWidth: 140,
      minWidth: 80,
    },
    {
      columnName: "Deactivedate",
      accessor: "DEACTIVE_DATE",
      sequence: 17,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      maxWidth: 150,
      minWidth: 90,
    },
    {
      columnName: "VerifiedBy",
      accessor: "VERIFIED_BY",
      sequence: 18,
      componentType: "default",
      width: 110,
      maxWidth: 140,
      minWidth: 80,
    },
    {
      columnName: "VerifiedDate",
      accessor: "VERIFIED_DATE",
      sequence: 19,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      maxWidth: 150,
      minWidth: 90,
    },
    {
      columnName: "FrequencyValue",
      accessor: "FEQ_VALUE",
      sequence: 20,
      componentType: "default",
      alignment: "right",
      width: 130,
      maxWidth: 160,
      minWidth: 100,
    },
    {
      columnName: "SINumber",
      accessor: "SI_NUMBER",
      sequence: 21,
      componentType: "default",
      alignment: "right",
      width: 110,
      maxWidth: 140,
      minWidth: 80,
    },
  ],
};
