import { GridMetaDataType } from "@acuteinfo/common-base";
export const EquitableMortgageGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 100,
      maxWidth: 100,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 35],
    defaultPageSize: 15,
    containerHeight: {
      min: "65vh",
      max: "65vh",
    },
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "SR_NO",
      isAutoSequence: true,
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 120,
    },
    {
      accessor: "TRAN_CD",
      columnName: "E. M. No",
      sequence: 2,
      alignment: "center",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Property Holder Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "MORTGAGE_DATE",
      columnName: "Mortgage Registration Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      isReadOnly: true,
      width: 190,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "MORT_EXP_DT",
      columnName: "Mortgage Expired Date",
      sequence: 5,
      alignment: "center",
      componentType: "date",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "REGISTERED_VIDE",
      columnName: "Registered Vide",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "STAMP_RS",
      columnName: "Stamp Rs",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 160,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Entered By",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 100,
      maxWidth: 250,
    },
  ],
};
