import { MasterDetailsMetaData } from "@acuteinfo/common-base";
import * as API from "../../../../api";
import { PREVENT_SPECIAL_CHAR } from "components/utilFunction/constant";

export const DocMasterDTLMetadata: MasterDetailsMetaData = {
  masterForm: {
    form: {
      name: "extdocumentmasterform",
      label: "KYCDocumentView",
      resetFieldOnUnmount: false,
      validationRun: "onBlur",
      render: {
        ordering: "auto",
        renderType: "simple",
        gridConfig: {
          item: {
            xs: 12,
            sm: 4,
            md: 4,
          },
          container: {
            direction: "row",
            spacing: 0.5,
          },
        },
      },
    },
    fields: [
      {
        render: { componentType: "select" },
        name: "TEMPLATE_CD",
        label: "Document",
        options: (dependentValue?, formState?, _?, authState?) =>
          API.getCustDocumentOpDtl({
            COMP_CD: authState?.companyID,
            BRANCH_CD: authState?.user?.branchCode,
            formState,
          }),
        _optionsKey: "getKYCDocumentTypes",
        placeholder: "",
        disableCaching: true,
        // defaultOptionLabel: "Select Document",
        required: true,
        // defaultValue: "21",
        // maxLength: 300,
        // showMaxLength: false,
        GridProps: { xs: 12, md: 4, sm: 4, lg: 4, xl: 3 },
        fullWidth: true,
        // validate: "getValidateValue",
        // autoComplete: "off",
        schemaValidation: {
          type: "string",
          rules: [{ name: "required", params: ["DocumentTypeIsRequired"] }],
        },
        isReadOnly: false,
        isFieldFocused: true,
        __EDIT__: { isReadOnly: true, isFieldFocused: false },
      },
      {
        render: { componentType: "textField" },
        name: "DOC_NO",
        label: "DocumentNo",
        placeholder: "",
        required: true,
        GridProps: { xs: 12, md: 4, sm: 4 },
        autoComplete: "off",
        schemaValidation: {
          type: "string",
          rules: [{ name: "required", params: ["DocumentNoIsRequired"] }],
        },
        preventSpecialChars: PREVENT_SPECIAL_CHAR.SPECIAL_CHARACTER,
        validate: (columnValue) => API.validateAlphaNumValue(columnValue),
        __EDIT__: { isReadOnly: false },
      },
      {
        render: { componentType: "datePicker" },
        name: "VALID_UPTO",
        label: "ValidTillDate",
        placeholder: "",
        required: true,
        GridProps: { xs: 12, md: 4, sm: 4 },
        autoComplete: "off",
        schemaValidation: {
          type: "date",
          rules: [
            { name: "required", params: ["ValidTillDateisrequired"] },
            { name: "typeError", params: ["Mustbeavaliddate"] },
            {
              name: "min",
              params: [new Date(), "PastDateNotAllowed"],
            },
          ],
        },
        __EDIT__: { isReadOnly: false },
      },
      {
        render: { componentType: "checkbox" },
        defaultValue: true,
        name: "SUBMIT",
        label: "Submit",
        GridProps: { xs: 12, md: 2, sm: 2 },
        __VIEW__: { IsReadOnly: true },
        // __EDIT__: { render: { componentType: "checkbox" } },
      },
      {
        render: { componentType: "hidden" },
        name: "TRAN_CD",
      },
      {
        render: { componentType: "hidden" },
        name: "SR_CD",
      },
    ],
  },
  detailsGrid: {
    gridConfig: {
      dense: true,
      gridLabel: "DocumentFiles",
      rowIdColumn: "LINE_CD",
      defaultColumnConfig: { width: 150, maxWidth: 250, minWidth: 100 },
      allowColumnReordering: true,
      hideHeader: true,
      disableGroupBy: true,
      // enablePagination: true,
      containerHeight: { min: "40vh", max: "40vh" },
      allowRowSelection: false,
      hiddenFlag: "_hidden",
      disableLoader: true,
    },
    columns: [
      {
        accessor: "LINE_CD",
        columnName: "PageNo",
        componentType: "editableNumberFormat",
        sequence: 1,
        alignment: "right",
        width: 70,
        maxWidth: 150,
        minWidth: 60,
        isAutoSequence: true,
      },
      {
        accessor: "VALID_UPTO",
        columnName: "ValidUpto",
        componentType: "editableDatePicker",
        sequence: 2,
        // alignment: "right",
        width: 180,
        maxWidth: 250,
        minWidth: 150,
        required: true,
        schemaValidation: {
          type: "date",
          rules: [
            { name: "required", params: ["ValidUptoIsRequired"] },
            { name: "typeError", params: ["Mustbeavaliddate"] },
            {
              name: "min",
              params: [new Date(), "PastDateNotAllowed"],
            },
          ],
        },
        isReadOnly: true,
      },
      {
        accessor: "DOC_IMAGE",
        columnName: "File",
        componentType: "default",
        sequence: 3,
        isVisible: false,
      },
      {
        accessor: "IMG_TYPE",
        columnName: "FileType",
        componentType: "default",
        sequence: 4,
        isVisible: false,
      },
      {
        columnName: "",
        componentType: "buttonRowCell",
        accessor: "VIEW_DETAIL",
        sequence: 11,
        buttonLabel: "ViewDtl",
        width: 150,
        minWidth: 130,
        maxWidth: 200,
        // isVisible: false,
        isVisibleInNew: true,
        __EDIT__: { isVisible: true },
        // __NEW__: { isVisible: true },
        // __VIEW__: { isVisible: false },
      },
      // {
      //   columnName: "Action",
      //   componentType: "deleteRowCell",
      //   accessor: "_hidden",
      //   sequence: 12,
      //   width: 100,
      //   minWidth: 80,
      //   maxWidth: 200,
      // },
    ],
  },
};
