export const advConfMstFormMetadata = {
  gridConfig: {
    dense: true,
    gridLabel: "Document Detail",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: { width: 150, maxWidth: 250, minWidth: 100 },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: false,
    containerHeight: { min: "29vh", max: "29vh" },
    allowRowSelection: false,
    hiddenFlag: "_hidden",
    disableLoader: false,
  },
  columns: [
    {
      accessor: "SR_CDZ",
      columnName: "SrNo",
      componentType: "default",
      sequence: 1,
      alignment: "center",
      width: 75,
      minWidth: 50,
      maxWidth: 100,
      isAutoSequence: true,
    },

    {
      accessor: "DOC_DESCRIPTION",
      columnName: "Documents",
      componentType: "default",
      sequence: 2,
      alignment: "left",
      isReadOnly: true,
      width: 350,
      minWidth: 200,
      maxWidth: 400,
    },
    {
      accessor: "SUBMIT",
      columnName: "Submit",
      componentType: "editableCheckbox",
      alignment: "center",
      isReadOnly: true,
      sequence: 2,
      width: 85,
      minWidth: 70,
      maxWidth: 120,
    },

    {
      accessor: "VALID_UPTO",
      columnName: "ValidTillDate",
      componentType: "editableDatePicker",
      alignment: "center",
      isReadOnly: true,
      sequence: 2,
      width: 210,
      minWidth: 100,
      maxWidth: 300,
    },
  ],
};
