import { GridMetaDataType } from "@acuteinfo/common-base";

export const gridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "INDEX",
    defaultColumnConfig: {
      width: 350,
      minWidth: 300,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 50, 100],
    defaultPageSize: 20,
    containerHeight: {
      min: "70vh",
      max: "70vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 150,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_CD",
      columnName: "RegistrationNo",
      sequence: 2,
      alignment: "right",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "TRAN_DT",
      columnName: "TransactionDate",
      sequence: 3,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 150,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "INSURANCE_DISP",
      columnName: "insuaranceThrogh",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 270,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "ACCT_NO",
      columnName: "AccountNum",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "ACCT_NM",
      columnName: "AccountName",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 270,
      minWidth: 150,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "PENDING_FLAG",
      columnName: "ConfirmStatus",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      color: (val, data) => {
        let PENDING_FLAG = data?.original?.CONFIRMED ?? "";
        return PENDING_FLAG === "Y" ? "green" : "red";
      },
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Created By",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 180,
    },
    {
      accessor: "CUSTOMER_ID",
      columnName: "CustomerId",
      sequence: 9,
      alignment: "right",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "PREMIUM_AMT",
      columnName: "PremiumAmount",
      sequence: 10,
      alignment: "right",
      isDisplayTotal: true,
      componentType: "currency",
      width: 150,
      minWidth: 150,
      maxWidth: 250,
    },
  ],
};
export const pmbyListGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 350,
      minWidth: 300,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: true,
    disableGroupBy: true,
    enablePagination: false,
    pageSizes: [20, 50, 100],
    defaultPageSize: 20,
    containerHeight: {
      min: "30vh",
      max: "30vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 150,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_CD",
      columnName: "RegistrationNo",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "CUSTOMER_ID",
      columnName: "CustomerId",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "APPLICANT_NM",
      columnName: "applicantName",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 270,
      minWidth: 150,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "INSURANCE_TRAN_CD",
      columnName: "insuranceName",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 270,
      minWidth: 150,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "ACTIVE",
      columnName: "Status",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      color: (val, data) => {
        let ACTIVE = data?.original?.ACTIVE ?? "";
        return ACTIVE === "Inactive" ? "red" : "green";
      },
    },
    {
      accessor: "MEM_STATUS_DISP",
      columnName: "memberStatus",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      color: (val, data) => {
        let MEM_STATUS_DISP = data?.original?.MEM_STATUS_DISP ?? "";
        return MEM_STATUS_DISP === "Eligible" ? "green" : "red";
      },
    },

    {
      accessor: "ENTERED_DATE",
      columnName: "EnteredDate",
      sequence: 8,
      alignment: "center",
      componentType: "date",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
      dateFormat: "dd/MM/yyyy",
    },
    {
      accessor: "ENTERED_BRANCH_CD",
      columnName: "enteredBranch",
      sequence: 9,
      alignment: "right",
      componentType: "default",
      width: 110,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "PREMIUM_PAID_DT",
      columnName: "premiumPaidDt",
      sequence: 10,
      alignment: "center",
      componentType: "date",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
      dateFormat: "dd/MM/yyyy",
    },
    {
      accessor: "CONFIRMED_DISP",
      columnName: "ConfirmationStatus",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      color: (val, data) => {
        let CONFIRMED_DISP = data?.original?.CONFIRMED_DISP ?? "";
        return CONFIRMED_DISP === "Confirmed" ? "green" : "red";
      },
    },
  ],
};
