import { GridMetaDataType } from "@acuteinfo/common-base";
export const PhotoHistoryMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Photo & Signature History",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 100,
      maxWidth: 100,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 35],
    defaultPageSize: 15,
    containerHeight: {
      min: "20vh",
      max: "40vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    paginationText: "TotalPhotoSignatureScanCount",
  },
  columns: [
    {
      accessor: "SR_NO",
      isAutoSequence: true,
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      accessor: "CUST_PHOTO",
      columnName: "PhotoImage",
      sequence: 2,
      alignment: "center",
      componentType: "icondefault",
      width: 100,
      minWidth: 50,
      maxWidth: 200,
    },
    {
      accessor: "CUST_SIGN",
      columnName: "SignImage",
      sequence: 3,
      alignment: "center",
      componentType: "icondefault",
      width: 100,
      minWidth: 50,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "EnteredBy",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 50,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "EnteredDate",
      sequence: 5,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "MACHINE_NM",
      columnName: "MachineName",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 100,
      maxWidth: 350,
    },
    {
      accessor: "VERIFIED_BY",
      columnName: "VerifiedBy",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 50,
      maxWidth: 200,
    },
    {
      accessor: "VERIFIED_DATE",
      columnName: "VerifiedDate",
      sequence: 8,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "CONF_DISP",
      columnName: "ConfStatus",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 90,
      minWidth: 50,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_BRANCH_CD",
      columnName: "EnteredBranch",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 50,
      maxWidth: 200,
    },
    {
      accessor: "ACT_FLAG",
      columnName: "Active",
      componentType: "editableCheckbox",
      sequence: 11,
      isReadOnly: true,
      alignment: "center",
      width: 60,
      minWidth: 30,
      maxWidth: 100,
    },
  ],
};
