import { GridMetaDataType } from "@acuteinfo/common-base";

export const Customer360GridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "SearchCriteriaData",
    rowIdColumn: "CUSTOMER_ID",
    searchPlaceholder: "Accounts",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "100vh",
      max: "100vh",
    },
    occupiedHeight: {
      min: "470px",
      max: "470px",
    },
    allowFilter: false,
    allowColumnHiding: false,
    isCusrsorFocused: true,
    allowRowSelection: false,
  },
  // filters: [],
  columns: [
    {
      columnName: "Branch",
      accessor: "BRANCH_CD",
      sequence: 1,
      componentType: "default",
      width: 60,
      minWidth: 60,
      maxWidth: 160,
      alignment: "left",
    },
    {
      accessor: "CUSTOMER_ID",
      columnName: "CustomerId",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 60,
      maxWidth: 120,
    },
    {
      accessor: "CUST_TYPE_DISP",
      columnName: "CustType",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 60,
      maxWidth: 120,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Account_Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 280,
      minWidth: 180,
      isReadOnly: true,
      maxWidth: 300,
    },
    {
      accessor: "ACCT_CNT",
      columnName: "AcCount",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 80,
      minWidth: 70,
      isReadOnly: true,
      maxWidth: 300,
    },

    {
      accessor: "JOINT_CNT",
      columnName: "JointAcCount",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 80,
      minWidth: 70,
      isReadOnly: true,
      maxWidth: 100,
    },
    {
      accessor: "NET_BANKING_INDICATOR",
      columnName: "NetBanking",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 70,
      isReadOnly: true,
      maxWidth: 100,
    },
    {
      accessor: "ATM_INDICATOR",
      columnName: "ATM",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 70,
      isReadOnly: true,
      maxWidth: 100,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "OpeningDate",
      sequence: 9,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      isReadOnly: true,
      width: 110,
      minWidth: 100,
      maxWidth: 140,
    },
    {
      accessor: "CONTACT2",
      columnName: "MobileNo",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 110,
      maxWidth: 180,
    },

    {
      accessor: "PAN_NO",
      columnName: "PAN_NO",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "ADD1",
      columnName: "Add1",
      sequence: 12,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "ADD2",
      columnName: "Add2",
      sequence: 13,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "EXTERNAL_ID",
      columnName: "ExemptionForm",
      sequence: 14,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      columnName: "MemAcctType",
      accessor: "MEM_ACCT_TYPE",
      sequence: 15,
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 160,
      alignment: "left",
    },
    {
      accessor: "MEM_ACCT_CD",
      columnName: "MemAccountNo",
      sequence: 16,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "REFERENCE_CUST_ID",
      columnName: "ReferenceCustomerId",
      sequence: 17,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "ELECTION_CARD_NO",
      columnName: "ElectionCardNo",
      sequence: 18,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "UNIQUE_ID",
      columnName: "UniqueAdharNo",
      sequence: 19,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "DRIVING_LICENSE_NO",
      columnName: "DrivingLicenseNo",
      sequence: 20,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "PASSPORT_NO",
      columnName: "PassportNo",
      sequence: 21,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 140,
      maxWidth: 180,
    },
  ],
};
