import { GridMetaDataType } from "@acuteinfo/common-base";
export const FDIntScheduleGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "InterestDetails",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 250,
      maxWidth: 300,
      minWidth: 200,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: false,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "45vh",
      max: "45vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },

  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "INT_TO_DATE",
      columnName: "IntDate",
      sequence: 2,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 170,
      minWidth: 110,
      maxWidth: 300,
    },
    {
      accessor: "INT_AMT",
      columnName: "IntAmount",
      sequence: 3,
      alignment: "right",
      componentType: "currency",
      width: 170,
      minWidth: 110,
      maxWidth: 300,
    },
    {
      accessor: "BAL",
      columnName: "IntAndPrincipal",
      sequence: 4,
      alignment: "right",
      componentType: "currency",
      width: 170,
      minWidth: 110,
      maxWidth: 300,
    },
  ],
};
