import { GridMetaDataType } from "@acuteinfo/common-base";
export const snapShotGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "SnapShot",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "23.7vh",
      max: "23.7vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
      isAutoSequence: true,
      alignment: "right",
    },
    {
      columnName: "TranDate",
      accessor: "TRN_DATE",
      sequence: 2,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 130,
    },
    {
      columnName: "ValueDate",
      accessor: "VALUE_DT",
      sequence: 3,
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      alignment: "center",
      width: 130,
    },

    {
      columnName: "narration",
      accessor: "REMARKS",
      sequence: 4,
      componentType: "default",
      width: 250,
      showTooltip: true,
    },
    {
      columnName: "Trx",
      accessor: "TYPE_CD",
      sequence: 5,
      componentType: "default",
      alignment: "right",
      width: 70,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "ChequeNo",
      accessor: "CHEQUE_NO",
      sequence: 6,
      componentType: "default",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "Debit",
      accessor: "DR_AMT",
      sequence: 7,
      componentType: "currency",
      currencyRefColumn: "CURRENCY_CD",
      width: 150,
      color: "red",
      alignment: "right",
      isTotalWithCurrency: true,
      totalDecimalCount: 2,
    },
    {
      columnName: "Credit",
      accessor: "CR_AMT",
      sequence: 8,
      componentType: "currency",
      currencyRefColumn: "CURRENCY_CD",
      width: 150,
      color: "green",
      alignment: "right",
      isTotalWithCurrency: true,
      totalDecimalCount: 2,
    },

    {
      columnName: "ClosingBalance",
      accessor: "CL_BAL",
      sequence: 9,
      componentType: "currency",
      currencyRefColumn: "CURRENCY_CD",
      width: 150,
      alignment: "right",
    },
    {
      columnName: "Branch",
      accessor: "ENTERED_BRANCH_CD",
      sequence: 10,
      componentType: "default",
      alignment: "right",
      width: 70,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "SDC",
      accessor: "SDC",
      sequence: 11,
      componentType: "default",
      width: 70,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "",
      componentType: "buttonRowCell",
      buttonLabel: "*",
      accessor: "CHEQUE_IMG",
      width: 80,
      sequence: 12,
      alignment: "center",
      isVisible: true,
      shouldExclude: (initialValue, original, prevRows, nextRows) => {
        if (original?.TYPE_CD === "5") {
          return false;
        } else {
          return true;
        }
      },
    },
    {
      columnName: "Maker",
      accessor: "MAKER",
      sequence: 13,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Checker",
      accessor: "CHECKER",
      sequence: 14,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "EnteredDate",
      accessor: "ENTRY_DT",
      sequence: 15,
      componentType: "date",
      dateFormat: "dd-MM-yyyy hh:mm:ss a",
      alignment: "center",
      width: 200,
      minWidth: 150,
      maxWidth: 250,
    },
  ],
};
