import { GridMetaDataType } from "@acuteinfo/common-base";

export const DupPanDetailGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "CUSTOMER_ID",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    allowRowSelection: false,
    disableSorting: true,
    disableGroupBy: true,
    enablePagination: true,
    defaultPageSize: 15,
    pageSizes: [15, 30, 50],
    containerHeight: {
      min: "55vh",
      max: "55vh",
    },
    allowColumnHiding: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "CUSTOMER_ID",
      columnName: "customerId",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Name",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "CUSTOMER_TYPE",
      columnName: "Type",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "MODIFIED_DATE",
      columnName: "ModifiedDate",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss a",
      width: 170,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      accessor: "NEW_VALUE",
      columnName: "NewValue",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 300,
    },
    {
      accessor: "MODIFIED_BY",
      columnName: "ModifiedBy",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
